config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

class ProxySubdomain
  def self.matches? req
    req.subdomain.present? && req.subdomain != "www"
  end
end
class NoSubdomain
  def self.matches? req
    !req.subdomain.present? || (req.subdomain.present? && req.subdomain == "www")
  end
end
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations]
  devise_scope :user do
    unauthenticated do
      get "/" =>  "devise/sessions#new"
    end
    authenticated :user do
      get '/users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
      put '/users/:id' => 'devise/registrations#update', as: 'registration'
    end
  end

  authenticated :user do
    constraints(ProxySubdomain) do
      mount Journalist::Middleman::Server, at: '/', as: 'proxy_root'
    end
  end

  constraints(NoSubdomain) do
    authenticated :user, lambda{|u| u.role == "ADMIN"} do
      mount Sidekiq::Web => "/sidekiq"
      namespace :admin do
        with_options except: :show do |t|
          t.resources :journals do
            t.resources :journal_accounts do
              with_options action: "set_status" do |map|
                map.post '/enable', action: "set_status"
                map.post '/disable', action: "set_status"
              end
            end
          end
          t.resources :user, except: :show
        end
      end
    end
    root to: "static_page#home"
    get '/journals/:id/access' => "journals#access", as: 'access_journal'
  end
end

app/views/layouts/shared/_errors.html.haml
- if object.errors.any?
  #error-explenation
    .alert.alert-danger
      The form contains #{pluralize(object.errors.count, "error")}.
    %ul
      - object.errors.full_messages.each do |msg|
        %li * #{msg}.
  %hr

app/views/layouts/shared/_flash.html.haml
- flash.each do |key, value|
  %div{class: flash_class(key), style: "display: none;"}
    %button.close &times;
    %span{class: flash_icon(key)}
    %strong= "#{message_status(key)} Message"
    %hr.message-inner-separator
    %p= raw(value)

app/views/layouts/shared/_menu.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Journalist", root_path, class: "navbar-brand"
    .collapse.navbar-collapse
      - if is_admin?
        %ul.nav.navbar-nav
          %li= link_to "User", admin_user_index_path
          %li= link_to "Journal", admin_journals_path
      - if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            = link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown" do
              %i.fa.fa-user
              = current_user.full_name
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to edit_user_registration_path do
                  %i.fa.fa-key
                  Edit Password
              %li
                = link_to destroy_user_session_path, method: :delete do
                  %i.fa.fa-power-off
                  Sign out