config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

class ProxySubdomain
  def self.matches? req
    req.subdomain.present? && req.subdomain != "www"
  end
end
class NoSubdomain
  def self.matches? req
    !req.subdomain.present? || (req.subdomain.present? && req.subdomain == "www")
  end
end
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations]
  devise_scope :user do
    unauthenticated do
      get "/" =>  "devise/sessions#new"
    end
    authenticated :user do
      get '/users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
      put '/users/:id' => 'devise/registrations#update', as: 'registration'
    end
  end

  authenticated :user do
    constraints(ProxySubdomain) do
      mount Journalist::Middleman::Server, at: '/', as: 'proxy_root'
    end
  end

  constraints(NoSubdomain) do
    authenticated :user, lambda{|u| u.role == "ADMIN"} do
      mount Sidekiq::Web => "/sidekiq"
      namespace :admin do
        with_options except: :show do |t|
          t.resources :journals do
            t.resources :journal_accounts do
              with_options action: "set_status" do |map|
                map.post '/enable', action: "set_status"
                map.post '/disable', action: "set_status"
              end
            end
          end
          t.resources :user, except: :show
        end
      end
    end
    root to: "static_page#home"
    get '/journals/:id/access' => "journals#access", as: 'access_journal'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLE = ["DEFAULT", "ADMIN"]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :async, 
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  validates_presence_of :full_name

  def is_admin?
    self.role == "ADMIN"
  end
end

app/controllers/admin/user_controller.rb
class Admin::UserController < ApplicationController
  before_action :admin_user!
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :remove_unused_params, only: :update

  def index
    respond_to do |format|
      format.html
      format.json {render json: UserDatatables.new(view_context)}
    end
  end

  def new
    @user = User.new
    respond_to do |format|
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        flash[:notice] = "User was successfuly created"
        format.js
      else
        format.js {render :new}
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        flash[:notice] = "User was successfuly updated"
        format.js
      else
        format.js {render :edit}
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_user_index_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end


  def user_params
    params.require(:user).permit(:full_name, :email, :role, :password, :password_confirmation)
  end

  def remove_unused_params
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
  end
end

app/views/admin/user/_form.html.haml
- url = @user.new_record? ? admin_user_index_path : admin_user_path(@user)
#user-modal.modal.fade{tabindex: "-1", role: "dialog", "aria-labelledby" => "userModalLabel", "aria-hidden" => "true", "data-backdrop" => "static", "data-keyboard" => "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: "button", "data-dismiss" => "modal", "aria-hidden" => "true"} &times;
        %h4#userModalLabel.modal-title
          = @user.new_record? ? "Create new user" : "Edit user"
      = form_for @user, url: url, remote: true, html: {role: "form", class: "form-horizontal"} do |f|
        .modal-body
          = render "layouts/shared/errors", object: f.object
          .form-group
            = f.label :full_name, "Full Name", class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :full_name, class: "form-control", placeholder: "User full name", autocomplete: "off", autofocus: true
          .form-group
            = f.label :email, "Email", class: "col-sm-3 control-label"
            .col-sm-9
              = f.email_field :email, class: "form-control", placeholder: "User email", autocomplete: "off"
          .form-group
            = f.label :role, "Role", class: "col-sm-3 control-label"
            .col-sm-9
              = f.select :role, options_for_select(User::ROLE, selected: @user.role), {}, {class: "form-control"}
          %legend Credential
          .form-group
            = f.label :password, "Password", class: "col-sm-3 control-label"
            .col-sm-9
              = f.password_field :password, class: "form-control", placeholder: "User password", autocomplete: "off"
          .form-group
            = f.label :password_confirmation, "Password confirmation", class: "col-sm-3 control-label"
            .col-sm-9
              = f.password_field :password_confirmation, class: "form-control", placeholder: "User password confirmation", autocomplete: "off"
          .modal-footer
            %button.btn.btn-primary{type: "submit"}
              %i.fa.fa-upload
              Save
            %button.btn.btn-default{type: "button", "data-dismiss" => "modal"}
              %i.fa.fa-times
              Cancel

app/views/admin/user/create.js.erb
<% content_for :additional_js do %>
  var a = $("#user-tables").dataTable();
  a._fnAjaxUpdate();
<%end%>
<%= render partial: "layouts/shared/javascripts/responder", locals: { selector: "#user-modal"} %>

app/views/admin/user/edit.js.erb
<% html = j render('form') %>
<%= render partial: "layouts/shared/javascripts/show_modal", locals: {template: html, selector: "#user-modal"} %>

app/views/admin/user/index.html.haml
- provide(:title, "Manage User")
#users
  %header
    .col-md-12
      .row
        .col-md-6
          %h2 Manage User
        .col-md-6
          .action{style: "margin-top: 20px;"}
            .pull-right
              = link_to new_admin_user_path, class: "btn btn-primary btn-lg", remote: true do
                %i.fa.fa-user
                Add User
    .clearfix
  %hr
  %section
    %table#user-tables.table.table-bordered{"data-url" => admin_user_index_path(format: "json")}
      %thead
        %tr
          %th
            .text-center Full name
          %th
            .text-center Email
          %th
            .text-center Role
          %th
            .text-center Created at
          %th
            .text-center Action

app/views/admin/user/new.js.erb
<% html = j render('form') %>
<%= render partial: "layouts/shared/javascripts/show_modal", locals: {template: html, selector: "#user-modal"} %>

app/views/admin/user/update.js.erb
<% content_for :additional_js do %>
  var a = $("#user-tables").dataTable();
  a._fnAjaxUpdate();
<%end%>
<%= render partial: "layouts/shared/javascripts/responder", locals: { selector: "#user-modal"} %>