config/routes.rb
require 'sidekiq/web'
require 'sidetiq/web'

class ProxySubdomain
  def self.matches? req
    req.subdomain.present? && req.subdomain != "www"
  end
end
class NoSubdomain
  def self.matches? req
    !req.subdomain.present? || (req.subdomain.present? && req.subdomain == "www")
  end
end
Rails.application.routes.draw do

  devise_for :users, skip: [:registrations]
  devise_scope :user do
    unauthenticated do
      get "/" =>  "devise/sessions#new"
    end
    authenticated :user do
      get '/users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
      put '/users/:id' => 'devise/registrations#update', as: 'registration'
    end
  end

  authenticated :user do
    constraints(ProxySubdomain) do
      mount Journalist::Middleman::Server, at: '/', as: 'proxy_root'
    end
  end

  constraints(NoSubdomain) do
    authenticated :user, lambda{|u| u.role == "ADMIN"} do
      mount Sidekiq::Web => "/sidekiq"
      namespace :admin do
        with_options except: :show do |t|
          t.resources :journals do
            t.resources :journal_accounts do
              with_options action: "set_status" do |map|
                map.post '/enable', action: "set_status"
                map.post '/disable', action: "set_status"
              end
            end
          end
          t.resources :user, except: :show
        end
      end
    end
    root to: "static_page#home"
    get '/journals/:id/access' => "journals#access", as: 'access_journal'
  end
end

app/models/journal.rb
class Journal < ActiveRecord::Base
  include Journalist::Models::Journal
end

app/controllers/admin/journals_controller.rb
class Admin::JournalsController < ApplicationController
  before_action :admin_user!
  before_action :set_journal, only: [:show, :edit, :update, :destroy]

  # GET /journals
  # GET /journals.json
  def index
    respond_to do |format|
      format.html
      format.json {render json: JournalDatatables.new(view_context)}
    end
  end

  # GET /journals/new
  def new
    @journal = Journal.new
    respond_to do |format|
      format.js
    end
  end

  # GET /journals/1/edit
  def edit
    respond_to do |format|
      format.js
    end
  end

  # POST /journals
  # POST /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        flash[:notice] = "Jounal resource was successfully created."
        format.js
      else
        format.js { render :new }
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        flash[:notice] = "Journal resource was successfuly updated"
        format.js
      else
        format.js { render :edit }
      end
    end
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to admin_journals_url, notice: 'Journal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.require(:journal).permit(:name, :driver, :request_domain)
    end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController

  def access
    journal = Journal.find(params[:id])
    create_instance journal
    redirect_to proxy_root_url(subdomain: journal.request_domain)
  end
end

app/views/admin/journals/_form.html.haml
#journal-modal.modal.fade{tabindex: "-1", role: "dialog", "aria-labelledby" => "journalModalLabel", "aria-hidden" => "true", "data-backdrop" => "static", "data-keyboard" => "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type: "button", "data-dismiss" => "modal", "aria-hidden" => "true"} &times;
        %h4#journalModalLabel.modal-title
          = @journal.new_record? ? "Create new journal resource" : "Edit journal resources"
      = form_for [:admin, @journal], remote: true, html: {role: "form", class: "form-horizontal"} do |f|
        .modal-body
          = render "layouts/shared/errors", object: f.object
          .form-group
            = f.label :name, "Name", class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :name, class: "form-control", placeholder: "Journal resources name"
          .form-group
            = f.label :request_domain, "Request domain", class: "col-sm-3 control-label"
            .col-sm-9
              = f.text_field :request_domain, class: "form-control", placeholder: "Request domain eg. 'google.com'"
              %span.help-block Not using www or http
          .form-group
            = f.label :driver, "Driver", class: "col-sm-3 control-label"
            .col-sm-9
              = f.select :driver, options_for_select(Journal::DRIVER, selected: @journal.driver), {}, {class: "form-control"}
          .modal-footer
            %button.btn.btn-primary{type: "submit"}
              %i.fa.fa-upload
              Save
            %button.btn.btn-default{type: "button", "data-dismiss" => "modal"}
              %i.fa.fa-times
              Cancel

app/views/admin/journals/create.js.erb
<% content_for :additional_js do %>
  var a = $("#journal-tables").dataTable();
  a._fnAjaxUpdate();
<%end%>
<%= render partial: "layouts/shared/javascripts/responder", locals: { selector: "#journal-modal"} %>

app/views/admin/journals/edit.js.erb
<% html = j render('form') %>
<%= render partial: "layouts/shared/javascripts/show_modal", locals: {template: html, selector: "#journal-modal"} %>

app/views/admin/journals/index.html.haml
- provide(:title, "Manage journal")
#journals
  %header
    .col-md-12
      .row
        .col-md-6
          %h2 Manage journal
        .col-md-6
          .action{style: "margin-top: 20px;"}
            .pull-right
              =link_to new_admin_journal_path, class: "btn btn-primary btn-lg", remote: true do
                %i.fa.fa-book
                Add Journal
    .clearfix
  %hr
  %section
    %table#journal-tables.table.table-bordered{"data-url" => admin_journals_path(format: "json")}
      %thead
        %tr
          %th
            .text-center Name
          %th
            .text-center Driver
          %th
            .text-center Journal Account
          %th
            .text-center Manage Journal Account
          %th
            .text-center Action

app/views/admin/journals/new.js.erb
<% html = j render('form') %>
<%= render partial: "layouts/shared/javascripts/show_modal", locals: {template: html, selector: "#journal-modal"} %>

app/views/admin/journals/update.js.erb
<% content_for :additional_js do %>
  var a = $("#journal-tables").dataTable();
  a._fnAjaxUpdate();
<%end%>
<%= render partial: "layouts/shared/javascripts/responder", locals: { selector: "#journal-modal"} %>